/**
 * Builds the chisme CLI into a standalone binary via `bun build --compile`.
 *
 * Default: build for the current platform, output ./chisme at the repo root.
 * `--all` (or `--release`): cross-compile every target into ./dist plus SHA256SUMS.
 *
 * For each target we embed the matching sqlite-vec loadable extension as a file
 * asset (so semantic vector search works in the standalone binary; see PLAN.md
 * Section 11). The embed works by temporarily rewriting src/embedded/vec-extension.ts
 * to import the copied extension, then restoring it afterwards. If a target's
 * extension is not present in node_modules (cross-platform packages are only
 * installed on matching hosts), that target builds keyword-only with a warning.
 */
import { resolve, join } from "node:path";
import { copyFileSync, existsSync, writeFileSync, mkdirSync, rmSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";

const CLI_DIR = import.meta.dir;
const ROOT = resolve(CLI_DIR, "../..");
const ENTRY = join(CLI_DIR, "src", "main.ts");
const EMBED_DIR = join(CLI_DIR, "src", "embedded");
const VEC_MODULE = join(EMBED_DIR, "vec-extension.ts");
const VEC_BIN = join(EMBED_DIR, "vec0.bin");
const DIST = join(ROOT, "dist");

const pkg = (await Bun.file(join(CLI_DIR, "package.json")).json()) as { version: string };
const VERSION = pkg.version;

interface TargetSpec {
  target: string;
  pkg: string;
  ext: string;
  out: string;
}

const TARGETS: Record<string, TargetSpec> = {
  "linux-x64": { target: "bun-linux-x64", pkg: "sqlite-vec-linux-x64", ext: "vec0.so", out: "chisme-linux-x64" },
  "linux-arm64": { target: "bun-linux-arm64", pkg: "sqlite-vec-linux-arm64", ext: "vec0.so", out: "chisme-linux-arm64" },
  "darwin-x64": { target: "bun-darwin-x64", pkg: "sqlite-vec-darwin-x64", ext: "vec0.dylib", out: "chisme-darwin-x64" },
  "darwin-arm64": { target: "bun-darwin-arm64", pkg: "sqlite-vec-darwin-arm64", ext: "vec0.dylib", out: "chisme-darwin-arm64" },
  "windows-x64": { target: "bun-windows-x64", pkg: "sqlite-vec-windows-x64", ext: "vec0.dll", out: "chisme-windows-x64.exe" },
};

function nativeKey(): string {
  const arch = process.arch === "arm64" ? "arm64" : "x64";
  const os = process.platform === "darwin" ? "darwin" : process.platform === "win32" ? "windows" : "linux";
  return `${os}-${arch}`;
}

function setVecModuleEmbedded(embedded: boolean): void {
  const body = embedded
    ? `// AUTO-GENERATED by build.ts during compile; restored to the committed placeholder afterwards.\n` +
      `import vec0Bin from "./vec0.bin" with { type: "file" };\n` +
      `export const vec0EmbeddedPath: string | null = vec0Bin;\n`
    : `export const vec0EmbeddedPath: string | null = null;\n`;
  writeFileSync(VEC_MODULE, body);
}

async function buildTarget(spec: TargetSpec, outfile: string): Promise<void> {
  const vecPath = join(ROOT, "node_modules", spec.pkg, spec.ext);
  const embedded = existsSync(vecPath);
  if (embedded) {
    copyFileSync(vecPath, VEC_BIN);
    setVecModuleEmbedded(true);
  } else {
    setVecModuleEmbedded(false);
    console.warn(`  warning: ${spec.pkg}/${spec.ext} not found; ${spec.out} will be keyword-only`);
  }

  const result = await Bun.build({
    entrypoints: [ENTRY],
    compile: { target: spec.target, outfile },
    minify: true,
    define: { BUILD_VERSION: JSON.stringify(VERSION) },
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`build failed for ${spec.target}`);
  }
  console.log(`  built ${outfile}${embedded ? " (semantic + keyword)" : " (keyword-only)"}`);
}

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

const all = process.argv.includes("--all") || process.argv.includes("--release");
const originalVecModule = await Bun.file(VEC_MODULE).text();

try {
  if (all) {
    mkdirSync(DIST, { recursive: true });
    const sums: string[] = [];
    for (const spec of Object.values(TARGETS)) {
      const outfile = join(DIST, spec.out);
      await buildTarget(spec, outfile);
      sums.push(`${sha256(outfile)}  ${spec.out}`);
    }
    writeFileSync(join(DIST, "SHA256SUMS"), sums.join("\n") + "\n");
    console.log(`\nWrote ${Object.keys(TARGETS).length} binaries + SHA256SUMS to ${DIST}`);
  } else {
    const key = nativeKey();
    const spec = TARGETS[key];
    if (!spec) throw new Error(`no build target for platform ${key}`);
    const outfile = join(ROOT, process.platform === "win32" ? "chisme.exe" : "chisme");
    await buildTarget(spec, outfile);
    console.log(`\nBuilt ${outfile}`);
  }
} finally {
  writeFileSync(VEC_MODULE, originalVecModule);
  if (existsSync(VEC_BIN)) rmSync(VEC_BIN);
}
