/**
 * Builds the chisme CLI into a standalone binary via `bun build --compile`.
 *
 * Default: build for the current platform, output ./chisme at the repo root.
 * `--all` (or `--release`): cross-compile every target into ./dist plus SHA256SUMS.
 *
 * Native dependencies are embedded so the standalone binary keeps full hybrid
 * search (see PLAN.md Sections 10 and 11):
 *  - sqlite-vec loadable extension (per-platform): embedded as vec0.bin and loaded
 *    at runtime. Cross-platform packages only install on a matching host, so a
 *    target whose extension is missing builds without vector storage.
 *  - onnxruntime-web WASM (platform-independent): embedded as ort-wasm.bin plus its
 *    mjs loader, so the embedder runs without a native addon. The binary cannot
 *    bundle onnxruntime-node / sharp (native addons), so those are stubbed out.
 *  - vanilla libsqlite3 (macOS only): embedded as libsqlite3.bin from the path in
 *    CHISME_MACOS_SQLITE_DYLIB. Apple's system SQLite disables loadable extensions,
 *    so without this sqlite-vec can't load and macOS is keyword-only. bun:sqlite is
 *    redirected to it via Database.setCustomSQLite() at runtime (see src/runtime/sqlite.ts).
 *
 * Each works by temporarily rewriting the placeholder modules under src/embedded/ to
 * import the copied assets, then restoring the placeholders afterwards.
 */
import { resolve, join } from "node:path";
import { copyFileSync, existsSync, writeFileSync, mkdirSync, rmSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";

const CLI_DIR = import.meta.dir;
const ROOT = resolve(CLI_DIR, "../..");
const ENTRY = join(CLI_DIR, "src", "main.ts");
const EMBED_DIR = join(CLI_DIR, "src", "embedded");
const VEC_MODULE = join(EMBED_DIR, "vec-extension.ts");
const VEC_BIN = join(EMBED_DIR, "vec0.bin");
const EMBEDDER_MODULE = join(EMBED_DIR, "embedder-assets.ts");
const WASM_BIN = join(EMBED_DIR, "ort-wasm.bin");
const LOADER_BIN = join(EMBED_DIR, "ort-wasm-loader.bin");
const SQLITE_MODULE = join(EMBED_DIR, "sqlite-lib.ts");
const SQLITE_BIN = join(EMBED_DIR, "libsqlite3.bin");
const ORT_WEB_DIST = join(ROOT, "node_modules", "onnxruntime-web", "dist");
const DIST = join(ROOT, "dist");

const pkg = (await Bun.file(join(CLI_DIR, "package.json")).json()) as { version: string };
const VERSION = pkg.version;

/**
 * transformers.js statically imports onnxruntime-node and sharp, both native
 * addons that cannot enter a --compile bundle. We never use them (text embeddings
 * run on the WASM backend), so resolve them to harmless stubs at build time.
 */
const stubNative: Bun.BunPlugin = {
  name: "stub-native",
  setup(build) {
    build.onResolve({ filter: /^(onnxruntime-node|sharp)$/ }, (args) => ({
      path: args.path,
      namespace: "native-stub",
    }));
    build.onLoad({ filter: /.*/, namespace: "native-stub" }, () => ({
      contents:
        "const noop = function(){}; export const InferenceSession = {}; export const Tensor = {}; export default noop;",
      loader: "js",
    }));
  },
};

interface TargetSpec {
  target: Bun.Build.CompileTarget;
  pkg: string;
  ext: string;
  out: string;
}

// biome-ignore format: keep the platform matrix as an aligned one-row-per-target table.
const TARGETS: Record<string, TargetSpec> = {
  "linux-x64": { target: "bun-linux-x64", pkg: "sqlite-vec-linux-x64", ext: "vec0.so", out: "chisme-linux-x64" },
  "linux-arm64": { target: "bun-linux-arm64", pkg: "sqlite-vec-linux-arm64", ext: "vec0.so", out: "chisme-linux-arm64" },
  "darwin-x64": { target: "bun-darwin-x64", pkg: "sqlite-vec-darwin-x64", ext: "vec0.dylib", out: "chisme-darwin-x64" },
  "darwin-arm64": { target: "bun-darwin-arm64", pkg: "sqlite-vec-darwin-arm64", ext: "vec0.dylib", out: "chisme-darwin-arm64" },
  "windows-x64": { target: "bun-windows-x64", pkg: "sqlite-vec-windows-x64", ext: "vec0.dll", out: "chisme-windows-x64.exe" },
};

function nativeKey(): string {
  const arch = process.arch === "arm64" ? "arm64" : "x64";
  const os =
    process.platform === "darwin" ? "darwin" : process.platform === "win32" ? "windows" : "linux";
  return `${os}-${arch}`;
}

function setVecModuleEmbedded(embedded: boolean): void {
  const body = embedded
    ? `// AUTO-GENERATED by build.ts during compile; restored to the committed placeholder afterwards.\n` +
      `import vec0Bin from "./vec0.bin" with { type: "file" };\n` +
      `export const vec0EmbeddedPath: string | null = vec0Bin;\n`
    : `export const vec0EmbeddedPath: string | null = null;\n`;
  writeFileSync(VEC_MODULE, body);
}

function setEmbedderEmbedded(embedded: boolean): void {
  const body = embedded
    ? `// AUTO-GENERATED by build.ts during compile; restored to the committed placeholder afterwards.\n` +
      `import wasmBin from "./ort-wasm.bin" with { type: "file" };\n` +
      `import loaderBin from "./ort-wasm-loader.bin" with { type: "file" };\n` +
      `export const embedderAssets: { wasm: string; loader: string } | null = { wasm: wasmBin, loader: loaderBin };\n`
    : `export const embedderAssets: { wasm: string; loader: string } | null = null;\n`;
  writeFileSync(EMBEDDER_MODULE, body);
}

function setSqliteModuleEmbedded(embedded: boolean): void {
  const body = embedded
    ? `// AUTO-GENERATED by build.ts during compile; restored to the committed placeholder afterwards.\n` +
      `import sqliteBin from "./libsqlite3.bin" with { type: "file" };\n` +
      `export const customSqliteEmbeddedPath: string | null = sqliteBin;\n`
    : `export const customSqliteEmbeddedPath: string | null = null;\n`;
  writeFileSync(SQLITE_MODULE, body);
}

async function buildTarget(spec: TargetSpec, outfile: string): Promise<void> {
  // sqlite-vec: per-platform native extension.
  const vecPath = join(ROOT, "node_modules", spec.pkg, spec.ext);
  const vecEmbedded = existsSync(vecPath);
  if (vecEmbedded) {
    copyFileSync(vecPath, VEC_BIN);
    setVecModuleEmbedded(true);
  } else {
    setVecModuleEmbedded(false);
    console.warn(`  warning: ${spec.pkg}/${spec.ext} not found; ${spec.out} loses vector storage`);
  }

  // onnxruntime-web: platform-independent WASM, embedded for every target.
  const wasmSrc = join(ORT_WEB_DIST, "ort-wasm-simd-threaded.wasm");
  const mjsSrc = join(ORT_WEB_DIST, "ort-wasm-simd-threaded.mjs");
  const embedderEmbedded = existsSync(wasmSrc) && existsSync(mjsSrc);
  if (embedderEmbedded) {
    copyFileSync(wasmSrc, WASM_BIN);
    copyFileSync(mjsSrc, LOADER_BIN);
    setEmbedderEmbedded(true);
  } else {
    setEmbedderEmbedded(false);
    console.warn(`  warning: onnxruntime-web WASM not found; ${spec.out} loses embeddings`);
  }

  // Vanilla SQLite for macOS targets: Apple's system SQLite (which Bun uses by
  // default) disables loadable extensions, so sqlite-vec can't load. Embed a
  // self-contained libsqlite3 built by CI (path in CHISME_MACOS_SQLITE_DYLIB) and
  // redirect bun:sqlite to it at runtime. Other targets need no custom SQLite.
  let sqliteEmbedded = false;
  if (spec.target.startsWith("bun-darwin")) {
    const dylib = process.env.CHISME_MACOS_SQLITE_DYLIB;
    if (dylib && existsSync(dylib)) {
      copyFileSync(dylib, SQLITE_BIN);
      setSqliteModuleEmbedded(true);
      sqliteEmbedded = true;
    } else {
      setSqliteModuleEmbedded(false);
      console.warn(
        `  warning: CHISME_MACOS_SQLITE_DYLIB not set/found; ${spec.out} falls back to system SQLite (semantic search disabled on macOS)`,
      );
    }
  } else {
    setSqliteModuleEmbedded(false);
  }

  const result = await Bun.build({
    entrypoints: [ENTRY],
    compile: { target: spec.target, outfile },
    minify: true,
    define: { BUILD_VERSION: JSON.stringify(VERSION) },
    plugins: [stubNative],
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error(`build failed for ${spec.target}`);
  }

  const caps = ["keyword"];
  if (vecEmbedded) caps.push("vector storage");
  if (embedderEmbedded) caps.push("embeddings");
  if (sqliteEmbedded) caps.push("custom sqlite");
  console.log(`  built ${outfile} (${caps.join(" + ")})`);
}

function sha256(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

const all = process.argv.includes("--all") || process.argv.includes("--release");
const originalVecModule = await Bun.file(VEC_MODULE).text();
const originalEmbedderModule = await Bun.file(EMBEDDER_MODULE).text();
const originalSqliteModule = await Bun.file(SQLITE_MODULE).text();

try {
  if (all) {
    mkdirSync(DIST, { recursive: true });
    const sums: string[] = [];
    for (const spec of Object.values(TARGETS)) {
      const outfile = join(DIST, spec.out);
      await buildTarget(spec, outfile);
      sums.push(`${sha256(outfile)}  ${spec.out}`);
    }
    writeFileSync(join(DIST, "SHA256SUMS"), `${sums.join("\n")}\n`);
    console.log(`\nWrote ${Object.keys(TARGETS).length} binaries + SHA256SUMS to ${DIST}`);
  } else {
    const key = nativeKey();
    const spec = TARGETS[key];
    if (!spec) throw new Error(`no build target for platform ${key}`);
    const outfile = join(ROOT, process.platform === "win32" ? "chisme.exe" : "chisme");
    await buildTarget(spec, outfile);
    console.log(`\nBuilt ${outfile}`);
  }
} finally {
  writeFileSync(VEC_MODULE, originalVecModule);
  writeFileSync(EMBEDDER_MODULE, originalEmbedderModule);
  writeFileSync(SQLITE_MODULE, originalSqliteModule);
  for (const f of [VEC_BIN, WASM_BIN, LOADER_BIN, SQLITE_BIN]) if (existsSync(f)) rmSync(f);
}
